### ISSUE TITLE
Error: qr_painter.dart line 100 column 25 - A value of type 'Future<Image>' can't be assigned to a variable of type 'Image'.

### ISSUE THREAD

**Issue by clovesmjunior** [lukef/qr.flutter#20]
Necessary to use await in call toImage:

101:25: Error: A value of type 'Future<Image>' can't be assigned to a
variable of type 'Image'.
 - 'Future' is from 'dart:async'.
 - 'Image' is from 'dart:ui'.
Try changing the type of the left hand side, or casting the right hand side to 'Image'.

Actual:
```
final ui.Image uiImage =
        toPicture(size).toImage(size.toInt(), size.toInt());
```

Correctly:

```
final ui.Image uiImage =
       await toPicture(size).toImage(size.toInt(), size.toInt());
```

**Comment by lukef** [comment]
Please use the 2.0.0-dev.1 tag. 

```
dependencies:
  qr_flutter:
    git:
      url: git://github.com/lukef/qr.flutter.git
      ref: 2.0.0-dev.1
```
