### ISSUE TITLE
Optimal version

### ISSUE THREAD

**Issue by felpsio** [lukef/qr.flutter#53]
I saw the optimal version is planned for the 3.00 version. Meanwhile I shipped it.

If anybody needs it for now can use my version until the next official version. Just add in the pubspec:

```
qr_flutter:
    git: https://github.com/felpsio/qr.flutter
```

**Comment by lukef** [comment]
Or you can just use the branch if you want.

```
dependencies:
  qr_flutter:
    git:
      url: https://github.com/lukef/qr.flutter
      ref: 3.0.0-dev
```
